# Generated by Django 4.2.18 on 2025-01-27 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_subscription_recipes_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='recipes_count',
            field=models.IntegerField(default=0, verbose_name='Кол-во рецептов'),
        ),
    ]
